redfin:
  target: dev
  outputs:
    dev:
      type: postgres
      host: {{ env_var('POSTGRES_HOST', 'localhost') }}
      user: {{ env_var('POSTGRES_USER', 'postgres') }}
      password: {{ env_var('POSTGRES_PASSWORD', 'postgres') }}
      port: {{ env_var('POSTGRES_PORT', '5432') }}
      dbname: {{ env_var('POSTGRES_DB', 'redfin') }}
      schema: public
      threads: 1
